### ISSUE TITLE
Coherence: overlap and orphan check

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/chalk#10]
Extend the code with the ability to do a coherence check. I'm not exactly sure what this should look like. To cover the orphan check, we'd have to include a knowledge of crates, but I think I'm more interested in examining the overlap check. That seems to imply a certain amount of negative reasoning (though that also includes some knowledge of crates).

**Comment by mikeyhew** [comment]
I'd like to work on this :) can you add some notes on how to do it?

**Comment by nikomatsakis** [comment]
Done by @sunjay 🎉

**Comment by sunjay** [comment]
Nice! :tada:
