### ISSUE TITLE
Abstract current IR using traits?

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/chalk#15]
Of course, it may be best to just re-implement this code in the compiler, but it's also worth considering if we can abstract away the current IR using traits to allow for integration into the compiler.

**Comment by withoutboats** [comment]
I would think the lowering traits would be sufficient for lowering integrating this into the compiler - just implement `LowerProgram` et al for the HIR types.

**Comment by nikomatsakis** [comment]
Yeah I think this is a silly bug to keep open.
