### ISSUE TITLE
model the algorithm for normalizing when trait is unknown

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/chalk#58]
Right now in Chalk we don't have support for types like `T::Item`; we always require fully explicit types like `<T as Iterator>::Item`. In particular, the trait is always known. So for example  [in the AST node, we know the trait](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/chalk-parse/src/ast.rs#L132-L136). In the lowered IR, a projection [references the id of a particular trait item](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/src/ir/mod.rs#L350-L354), and hence implicitly specifies a particular trait.

The rules in Rust are a bit hackily implemented but the *idea* is that we should permit `T::Item` only if there is a unique trait that could work, selected from the set of in-scope traits. I think the first step for this issue therefore is to model in-scope traits somehow. I'd probably want to do this with a new kind of [`DomainGoal`](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/src/ir/mod.rs#L388), something like `InScope(ItemId)`, where `ItemId` is the id of a trait. We would have to give this some syntax too (e.g., `InScope(Iterator)`). Then we can model which traits are in scope by adding those facts into the environment (e.g., `if (InScope(Iterator)) { .. })`).

Here are the steps to add `InScope`:

- Extend [the AST `WhereClause` struct](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/chalk-parse/src/ast.rs#L164-L171) to add something for `InScope(...)`.
- Extend [the parser](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/chalk-parse/src/parser.lalrpop#L144) to parse it.
- Extend [`DomainGoal` to include the new case `InScope(ItemId)`](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/src/ir/mod.rs#L388), as described before.
- Extend [the lowering code that converts a where-clause into a `DomainGoal`](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/src/lower/mod.rs#L386) to handle that case as well as [the lowering code that converts into a `LeafGoal`](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/src/lower/mod.rs#L416) (which can just invoke the other case, like [this arm does](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/src/lower/mod.rs#L421).
- Add some tests [like this one](https://github.com/nikomatsakis/chalk/blob/72e655355e237ff1b9fdaeb024e8e46569178e3c/src/solve/test.rs#L56), probably just checking that `InScope(Foo)` cannot be proven, but `if (InScope(Foo) { InScope(Foo) }` can.

Once that work is done, we can do the next half of *using* the in-scope facts to do something useful.

**Comment by nikomatsakis** [comment]
cc @Gargolun, who expressed some interest here.

**Comment by Garogolun** [comment]
Adding `InScope` went scaringly quickly, but maybe I missed something. The commit is [here](https://github.com/Garogolun/chalk/commit/ab6b21cee868a7f741830383d2228625aa82cf2b).

If I understand correctly, the next step is to add types such as `T::Item` (where the trait is not specified), and generate rules to infer `<T as Iterator>::Item` from `T::Item` and things like `InScope(Iterator)`? (I also tried thinking a bit about these rules, but I don't know what rustc does exactly.)

**Comment by nikomatsakis** [comment]
@Garogolun argh, sorry, I'm having trouble keeping up with GH notifications right now. Feel free to reach out over [gitter](https://gitter.im/chalk-rs/Lobby) for faster responses. =)

Anyway, that commit looks pretty reasonable. 

Yes, I think that the next step would be to add a new kind of type that is like an associated type but without the trait, and a rule like:

```
Normalize<Item>(A, B) :-
    InScope(Iterator),
    Normalize<Iterator::Item>(A, B).
```

**Comment by fabric-and-ink** [comment]
@Garogolun are you still on it? If not, I am interested in picking this up 🙂

**Comment by Garogolun** [comment]
@fabric-and-ink I'm actually on it right now. :smile: Should have something soon.

**Comment by nikomatsakis** [comment]
OK, this is done.
