### ISSUE TITLE
support overlap for marker traits

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/chalk#62]
The current coherence rules do not have any special cases for "marker traits" -- that is, traits with zero items. As [discussed](https://github.com/rust-lang-nursery/chalk/issues/8#issuecomment-336644098) in #8, at least for now it'd be nice to have "marker-ness" be declared explicitly with `#[marker]`. 

Here are some steps to do this:

We want to model this on the support for `#[auto]` trait declarations. This means we would:

- add a field to the ast for trait definitions ([like `auto`](https://github.com/rust-lang-nursery/chalk/blob/c8971c18294a7310010806a7283cdd417bec5c50/chalk-parse/src/ast.rs#L39))
- add the keyword to the parser ([like this](https://github.com/rust-lang-nursery/chalk/blob/c8971c18294a7310010806a7283cdd417bec5c50/chalk-parse/src/parser.lalrpop#L51-L63))
- add a field to [the `TraitDatumBound` struct](https://github.com/rust-lang-nursery/chalk/blob/c8971c18294a7310010806a7283cdd417bec5c50/src/ir/mod.rs#L243-L248), again, like `auto`
- In [the `visit_specializations` function](https://github.com/rust-lang-nursery/chalk/blob/c8971c18294a7310010806a7283cdd417bec5c50/src/coherence/solve.rs#L9), we can basically just ignore marker traits, I believe

It might be nice, rather than just adding another boolean field, to introduce some sort of `TraitFlags` type (e.g., `struct TraitFlags { auto: bool, marker: bool }`) into the AST and copy that over into `ir::TraitDatumBound`? Or at least I don't love having a bunch of random boolean variables floating around.

**Comment by nikomatsakis** [comment]
cc @mikeyhew 

cc @withoutboats -- do you think further changes are needd in coherence?

**Comment by lqd** [comment]
I'd like to try this if that's ok :)

@nikomatsakis to add the keyword to the parser, should we ensure `#[auto]` and `#[marker]` can or can't be used at the same time ? (maybe it doesn't matter).

Should we also add the `#[marker]` attribute to the other marker traits in the solver tests ?

btw I quickly prototyped the steps in the issue, and indeed nothing more seems to be needed to solve the problem.

**Comment by mikeyhew** [comment]
@lqd I was going to take this on, but I'm already busy with an issue from rust-lang/rust, and you seem to have a good idea of what needs to be done here, so go for it :) When I'm finished with the compiler issue, I'm sure @nikomatsakis will have more issues to work on for chalk.

`#[auto]` and `#[marker]` can both be used at the same time – think of `Send` and `Sync`. As for adding `#[marker]` to traits in the existing tests, that sounds like a good idea, but I'll let @nikomatsakis or @withoutboats direct you there. There is one test case though that I added in #61, `partial_overlap_3`, which currently doesn't pass, and should pass once you implement this and add a `#[marker]` attribute to the `Marker` trait.

**Comment by lqd** [comment]
@mikeyhew thanks for the comment ! As you mentioned, `partial_overlap_3` indeed passes successfully with #64
