### ISSUE TITLE
impl SuperTrait for T: SubTrait does not work

### ISSUE THREAD

**Issue by mikeyhew** [rust-lang-nursery/chalk#71]
The following works in Rust, but not in Chalk:

```
trait DynSized {}
trait Sized where Self: DynSized {}
impl<T> DynSized for T where T: Sized {}
struct i32 {}
impl Sized for i32 {}
```

For the goal `i32: DynSized`, Chalk currently returns "No possible solution", and it should return "Unique".

**Comment by mikeyhew** [comment]
It looks like this is an instance of #12

**Comment by scalexm** [comment]
@mikeyhew Yes, this is somehow a known bug, because of implied bounds not being completely implemented at the moment.

**Comment by mikeyhew** [comment]
@scalexm what do you mean by "implied bounds"?

**Comment by scalexm** [comment]
I mean things like "if `T` implements `Sized`, then `T` necessarily implements `DynSized`". For these kinds of affirmation to be correct, we must add some requirements on impls (called *well-formedness* requirements). Currently, these requirements are too restrictive, hence your code is not being accepted.

**Comment by mikeyhew** [comment]
@scalexm the above code _is_ accepted by chalk. I guess it just ignores it though?

**Comment by mikeyhew** [comment]
@scalexm I tried out your implied-bounds branch, but didn't notice any changes with the above code :/

**Comment by mikeyhew** [comment]
@scalexm Oh, I see... I saw that @nikomatsakis was reviewing it, and assumed it was otherwised good to go :smile:

**Comment by mikeyhew** [comment]
I'm gonna close this, since it is a duplicate of #12

**Comment by scalexm** [comment]
@mikeyhew PS: it works now

**Comment by mikeyhew** [comment]
@scalexm Sweet!

```rust
trait DynSized {}
trait Sized where Self: DynSized {}
impl<T> DynSized for T where T: Sized {}
struct i32 {}
impl Sized for i32 {}

// ?- i32: DynSized
// Unique; substitution [], lifetime constraints []
```
