### ISSUE TITLE
Will/could chalk allow rust to support logical programming ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [rust-lang-nursery/chalk#72]
I've read that chalk will be used internally by rustc for many things, but I Wonder if there is any plan for adding to rust (not only MIR) full/partial support for the logical programming paradigm?
https://en.wikipedia.org/wiki/Logic_programming?wprov=sfla1

I feel like this paradigm offer many possibilities (AI, etc) but it is not widely used because there is no great language and fast language that support it.
Disclaimer : I may say bullshit.

**Comment by nikomatsakis** [comment]
There's not really a plan for that thus far =) but I guess anything is possible!

You may be interested in <https://github.com/wartman4404/rust-kanren>. I've not looked closely at it but in general the MiniKanren series of projects aim to embed logic programming in other languages.
