### ISSUE TITLE
🔬 model open vs closed world

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/chalk#92]
In @aturon's epic blog post [Negative reasoning in chalk](https://aturon.github.io/blog/2017/04/24/negative-chalk/), he described using modal logic to model coherence. This seems like a great idea, but we've not done it in chalk. Let's get it done!

I guess the first thing to narrow down is just what we want. The overall goal is that certain kinds of negative queries fail. This is roughly corresponding to the logic described in [RFC 1023](https://rust-lang.github.io/rfcs/1023-rebalancing-coherence.html), though we should also consider how the code works, as there've been a few bug fixes and things in the meantime (and the definition of "orphans" is a bit tricky too). **But -- intuitively -- the goal is to limit reasoning about types/traits external to your crate. So e.g. if we ask `String: Iterator` -- and we are not compiling libstd :) -- this would come back as "maybe", reflecting the idea that maybe we'll add an impl like that in the future.**

I'll leave it here and put the rest in comments.

**Comment by nikomatsakis** [comment]
cc @Garogolun -- you had expressed interest in this

**Comment by nikomatsakis** [comment]
My hope was that we could model this without touching the core solver. Roughly speaking my idea was to build on the notion of external types/traits that @lqd added in https://github.com/rust-lang-nursery/chalk/pull/86.

Let's posit that we have a `External(Type)` predicate that is true if the given type is external, and that we have a special `OpenWorld` domain goal (along with the existing, special `CannotProve` domain goal).

Then, during lowering, for each external trait like `Iterator`, maybe we define a program clause like this one:

```rust
forall<T> {
  Implemented(T: Iterator) :-
    OpenWorld,
    External(T),
    CannotProve
}
```

Now if we go to prove `String: Iterator`, we will neither fail nor succeed, but get back an ambiguos result (same with `Not { String: Iterator }`).

**Comment by nikomatsakis** [comment]
@Garogolun plans to hack on this!

**Comment by nikomatsakis** [comment]
cc @Garogolun -- I haven't heard from you, I think @sunjay is going to take a few steps here though.

**Comment by nikomatsakis** [comment]
OK, so. @sunjay, in terms of background reading, I would recommend [RFC 1023](https://rust-lang.github.io/rfcs/1023-rebalancing-coherence.html), which covers the basic idea and rationale here. 

It appears that we have already a field `external` that marks structs or traits:

https://github.com/rust-lang-nursery/chalk/blob/b953f83c81d6737d5f717a45fde6c6f212751a35/chalk-parse/src/ast.rs#L35-L37

We need to add a new kind of goal (actually, maybe two) that is like `IsLocal(Ty)` and `IsLocal(TraitRef)`. Presumably that means adding variants to `DomainGoal`:

https://github.com/rust-lang-nursery/chalk/blob/b953f83c81d6737d5f717a45fde6c6f212751a35/src/ir/mod.rs#L504-L508

And then we need to add some rules into lowering for proving 

For some struct S<T> that is **not** marked as external, we would have:

```
forall<T> { IsLocal(S<T>). }
```

(Actually, we need a `#[fundamental]` tag too, but let's ignore that for now.)

For some trait ref like `T: Trait`, if the trait is not external, then there is a rule:

```
forall<T> {
  IsLocal(T: Trait)
}
```

If the trait *is* marked external, then it is local only if the types are local:

```
forall<T> {
  IsLocal(T: Trait) :- IsLocal(T)
}
```

We'll have to play with these rules, I haven't captured the full subtleties, but it's a start. =)

**Comment by sunjay** [comment]
@nikomatsakis I think this is completely done now. :tada: :smile:
